### ISSUE TITLE
Remove the up/down key bindings

### ISSUE THREAD

**Issue by ionutvmi** [kizza/Table-of-comments#10]
I would suggest we remove the default key bindings for moving up/down.
We should document how the user can configure them in the Key Binding - User file and not enforce them by default.

**Comment by ionutvmi** [comment]
The mouse binding seems ok to me but I think the same logic as above could be applied we should not enforce them on the user as they may already have some other action set on that key/mouse binding.

What do you guys think ?

**Comment by MalcolmK** [comment]
I agree. In fact I have been thinking the same last night. Maybe it is wise to add this as an default option. Something like this:

"traverse_by_key" : boolean   // Default set true.
"traverse_by_mouse" : boolean   // Default set true.
"key_up" : "arrow_up"   // Or whatever the official name is for the arrow up.
"key_down" : "arrow_down"   // Or whateveer the arrow down. 

Most packages provide a default key binding. But this way users can adjust it to their needs.

What do you think?

**Comment by ionutvmi** [comment]
I don't think this should be in the setting instead we should carefully document some examples of what the user insert in his `Key Binding - User`

Basically the same approach we have right now for the `f1` key in the readme.

**Comment by kizza** [comment]
Totally agree on this stuff btw (too much having it "auto on" as is not a core element).  Cheers!
