### ISSUE TITLE
Add some test files

### ISSUE THREAD

**Issue by ionutvmi** [kizza/Table-of-comments#11]
After having a look over the example.css file I think we should extend it to a tests/*.txt files so we can use it for testing in different edge cases with different configurations and regression testing.

In the future we could automate the testing process somehow.

**Comment by MalcolmK** [comment]
I think that is a good idea, but I am not thát good at python I can manage testing and stuff :) So maybe you can help with this?

**Comment by ionutvmi** [comment]
Yep, I already assigned it to myself I just wrote it here so we can discuss about it.
For now I don't have anything crazy in mind just some text files witch we can test manually for now and automate it in the near future.
I will look over it when I will get some free time.

**Comment by MalcolmK** [comment]
Okay! Sure, the same here. I maintain this project in my free time, so some periods I can do more than other periods :)

**Comment by kizza** [comment]
Sounds great. I've written a unit testcase package (simple one) for my other sublime plugin (as very much needed it) but have also seen a lot of github projects use Travis (https://travis-ci.org) as a free github enabled continuous integration testing server. In fact the sublime text package control uses it when submitting plugins. Obviously overkill at present - and agree @ionutvmi something simple to start is a good first step.

**Comment by kizza** [comment]
...I might chuck in the test package I have already to see what y'all think - but very happy to try something else as it develops.  (Essentially it let's you write test classes that open a new file, dumps some test text, runs the TOC command on the text then let's you check for expected results... and finallu dumps out a list of passed and failed tests.)

**Comment by kizza** [comment]
Have just uploaded the test suite infrastructure (to "Develop" branch) that can run within sublimetext... you can execute it from command palette (Ctrl + Shift + P)  as "Table of comments: Run Tests" (or set a keyboard shortcut to run "table_of_comments_run_tests" which is easier for development I find)

It's the unit test approach of test classes with test methods that setup the environment, execute the plugin and test the results... also lets us tweak plugin settings or file syntax for each test and check how that executes also.  Let me know what y'all think when digested (tested on ST2 and ST3) so should hopefully just execute for you guys first go.

**Comment by MalcolmK** [comment]
I think we have the test files. Shouldn't we close this issue?
