### ISSUE TITLE
Ascii Art title in install docs

### ISSUE THREAD

**Issue by MalcolmK** [kizza/Table-of-comments#15]
Hey Guys,

How about an ASCII art title in the install docs? I have pick some that I like. It was kinda hard to show them here as text, so these are screenshots:
<br />
<br />
__Banner:__
<br />
![image](https://cloud.githubusercontent.com/assets/2427717/5893045/6836cc24-a4d6-11e4-89d0-9f1dfd2814d9.png)
<br />
<br />
<br />
__Doom:__
<br />
![image](https://cloud.githubusercontent.com/assets/2427717/5893051/8903905e-a4d6-11e4-9203-446946a8a166.png)
<br />
<br />
<br />
__Epic:__
<br />
![image](https://cloud.githubusercontent.com/assets/2427717/5893052/943e9720-a4d6-11e4-8b7b-b716d42b27bf.png)
<br />
<br />
<br />
__Larry 3D:__
<br />
![image](https://cloud.githubusercontent.com/assets/2427717/5893054/a2c09fd2-a4d6-11e4-996d-055186a6357a.png)
<br />
<br />
<br />
__Ogre:__
<br />
![image](https://cloud.githubusercontent.com/assets/2427717/5893058/b3e628e0-a4d6-11e4-9437-f00cbdc4aeb4.png)
<br />
<br />
<br />
__Keyboard:__
<br />
![image](https://cloud.githubusercontent.com/assets/2427717/5893060/c1d53590-a4d6-11e4-910b-10d7ad6c1454.png)
<br />
<br />
<br />
What do you guys think? If you think the idea is crap at all, you can be honest ofc.

**Comment by ionutvmi** [comment]
:+1: 
I like the `Doom` or the `Larry 3D`

**Comment by MalcolmK** [comment]
@ionutvmi Thanks. And you @kizza, what do you think?

**Comment by kizza** [comment]
Cool stuff! I like the doom one also :)

**Comment by MalcolmK** [comment]
Okay, then I'm gonna put the dume inside the install documentent.

**Comment by ionutvmi** [comment]
Closing this as it is complete.
