### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by MalcolmK** [kizza/Table-of-comments#19]
The coding standard of Python is PEP8. I think the code would be improved if we would use this standard.

**Comment by kizza** [comment]
Cool. Sounds good. Does anyone know of a cool pep8 syntax code linter for sublinetext? I use SublineLinter for code... will brush up in my reading of pep8 (and so means four spaces indent rather than tab?). But yes better to use the standard.

**Comment by kizza** [comment]
(Got linter working from https://github.com/SublimeLinter/SublimeLinter-pep8)

**Comment by kizza** [comment]
Just pushed new develop version with pep8 done (might be some things I missed), but should be done

**Comment by ionutvmi** [comment]
looks ok to me
I will close this
