### ISSUE TITLE
The move up & down command stopped working

### ISSUE THREAD

**Issue by cheoAlejo** [kizza/Table-of-comments#22]
It's not working anymore, or maybe im missing something ?

**Comment by kizza** [comment]
Damn, I meant to get in touch with you! Sorry, the latest version removed the keyboard bindings from being enabled by default (the decision was that while cool, to be on by default for this plugin might be confusing)

You can check out the docs at https://github.com/kizza/Table-of-comments for adding the keybindings - let me know if it works for you but ultimately in user key bindings try

   { "keys": ["alt+up"],   "command": "table_of_comments", "args":{ "move":"up" } }
   { "keys": ["alt+down"], "command": "table_of_comments", "args":{ "move":"down" } }

Cheers

**Comment by cheoAlejo** [comment]
Sorry, I didn't mean keybindings, actually I changed them to f7 & shift+f7, I mean the whole command doesn't work, even if I run it from command pallette or from console.

**Comment by kizza** [comment]
Bummer. It literally had broken! Thanks for letting me know - I've fixed it and pushed the new version, you can manually update the plugin via cloning the latest release or package manager should sync it down soon enough.  Thanks again @cheoAlejo and sorry for breaking it so soon :)

**Comment by cheoAlejo** [comment]
:)
