### ISSUE TITLE
Using # as level_char yields false positives in CSS files

### ISSUE THREAD

**Issue by fvsch** [kizza/Table-of-comments#23]
First, I love this plugin. Wanted to write my own but I'm too novice in both Python and Sublime's API so I'm really glad you did. :)

We'd like to add an official comment pattern to our CSS code guide at work, and would like to use `#` as the identifier for headings. Why `#`? In order to match Markdown.

Using this code:
```css
/* # Header */
/* ## Container */
#header {
    background-color: #ff0000;
}
```
and these settings:
```json
{
    "toc_char"     : "-",
    "level_char"   : "#",
    "comment_chars": "/*#|"
}
```
Table of Comments' result is:
```
Header
- Container
header {
background-color: ff0000;
```

I was able to reproduce this issue with other characters, such as `@` (fun with `@media` and LESS variables) or `$` (plays nice with Sass variables).

For the record, this other (simpler) plugin does not seem to have this issue: https://github.com/arnaud-f/GoToMark/blob/master/GoToMark.py

**Comment by kizza** [comment]
Howdy @fvsch - thanks for getting in touch and yes you're totally right - the plugin uses sublimetext's syntax scope functions to only grab titles within comments - but there was a bug so wan't doing it correctly in this case!  Have just pushed out a new version - you can clone from master or package control will push the new update out soon enough.

Chuffed to hear you enjoy the plugin - glad it works for others also.  Let me know if you have any further things that pop up.
