### ISSUE TITLE
Automatically jump to line when focusing result

### ISSUE THREAD

**Issue by fvsch** [kizza/Table-of-comments#24]
I would love it if this plugin's list (the one toggled with "Table of Comments: Show") behaved more like the "Goto Symbol…" dialog:

- automatically scrolling the document to show the focused match;
- validating the position with Enter, returning to the initial position with Esc.

It's a great way to quickly "scan" a document.

If that's hard to do with Table of Comments' own dialog, maybe it would be possible to also populate the list of symbols with the detected comments, using a prefix to allow filtering?

**Comment by kizza** [comment]
Cool idea.  You may have seen in the readme that you can use keybindings to jump up and down between comment titles with keystrokes (which I happen to do with alt up an down)... but you're talking about having it happen when you press up and down between items in the popup quickjump panel yeah?  Will have a look at the api to see bout it.

**Comment by kizza** [comment]
Alright - turns out it's not possible with ST2, but IS available in the api for ST3.  So have built it in, and pushed a new version out.  Cheers for taking the time to get in touch and for the great idea - and hope it works well for ya!

**Comment by fvsch** [comment]
Thanks, I tried it and it works perfectly. :)

As a follow-up, I was wondering if it would be possible to select the title text instead of the entire comment line. The idea would be to match the “Goto Symbol…” behavior even more closely.

For instance if I have this code:
```
/* > My Title */
```
currently Table of Comments selects this:
```
[/* > My Title */]
```
and ideally it would select this:
```
/* > [My Title] */
```
so that if you want to change a heading, you can jump to it, and start typing right away. Changing the level would be facilitated too.

It's a small usability refinement, and if it's easy to do, it could be nice.
