### ISSUE TITLE
Comment ignored if it contains `>`

### ISSUE THREAD

**Issue by fvsch** [kizza/Table-of-comments#26]
With this code:

```scss
// > My Module (Test 1)

/* > My Module (Test 2) */

// > Modules => My Module (Test 3)

/* > Modules => My Module (Test 4) */
```
The third and fourth comments are ignored by Table of Comments. Apparently this is true of any comment that contains a `>` inside the title string, regardless of what `level_char` is set to, for instance with `"level_char": "#"`:

```scss
// # My Module (Test 1)
/* # My Module (Test 2) */
// # Modules > My Module (Test 3)
/* # Modules # My Module (Test 4) */
```
we get:
```
My Module (Test 1)
My Module (Test 2)
Modules  My Module (Test 4)
```
I suspect using `->` or `=>` in title comments would not be that uncommon.

**Comment by kizza** [comment]
Cheers @fvsch for following up with that - and @ionutvmi  for a great fix. Have merged it into develop - am planning to push a new release today with the better "selecting" of headings when jumping through them also

**Comment by kizza** [comment]
New version 1.1.4 has been pushed - bugs fixed, and title highlighting is smarter
