### ISSUE TITLE
`level_char`s inside titles are replaced with `toc_char`s

### ISSUE THREAD

**Issue by fvsch** [kizza/Table-of-comments#27]
It's a small thing but `level_char`s withing the title string seem to get removed altogether, regardless of where they appear in the string. Ideally they would be removed only at the start.

```
{ "level_char": "-" }
/* - Foo - Bar */
Result: "Foo  Bar"
Ideally: "Foo - Bar"

{ "level_char": "#" }
/* # Foo # Bar */
Result: "Foo  Bar"
Ideally: "Foo # Bar"
```

Actually it seems a bit more complex than just "removed", as this example shows (`"level_char": "!" `):

```
/* !! Some Module */
/* !! Some Module! */
/* !! Some Module(!) */
/* !!! Common to all instances (DO NOT CHANGE!) */
/* !!! Common to all instances (DO NOT CHANGE!!!) */
```

Results in this TOC:

```
/*
* TOC
*
* - Some Module
* - Some Module
* - Some Module(-)
* -- Common to all instances (DO NOT CHANGE-)
* -- Common to all instances (DO NOT CHANGE---)
*/
```
I understand trimming at the end (which allows `/* ## Level Two Title ## */` for instance), but I would avoid replacing instances of the `level_char` which are not at the beginning or the end with the `toc_char`.

**Comment by kizza** [comment]
(same here - all fixed in latest release).  Cheers as always for the feedback and help!

**Comment by fvsch** [comment]
Thanks @ionutvmi for the fixes!
