### ISSUE TITLE
When showing dialog, don't focus first heading

### ISSUE THREAD

**Issue by fvsch** [kizza/Table-of-comments#37]
Small usability bug. :)

Working on a 2k line file here. When showing the Table of Comments dialog, the first heading in the file is focused, which makes the view jump to:

- The beginning of the file
- Or wherever the first heading is (sometimes further down in the middle of the file)

Hitting ESC takes you back to the original position, so it's not that big a deal, but it can be jarring, especially if you don't have a heading yet for the part of the file you were working on *and* don't think about hitting ESC (or don't remember it). You can get lost easily.

Ideally, the first heading would not get focused until the user hits the Down key.

For the record, here's what "Goto Symbol…" does: it focuses the closest symbol that occurs before the original cursor position. Maybe that can be a good thing for Toc as well, I don't know.

**Comment by kizza** [comment]
Yeah, to be honest I noticed that....am have been slowly realising that it's annoying also :)
I'll make it select the current comment title - so that moving up or down starts where you are.
