### ISSUE TITLE
Move up command doesn't work when cursor is after last heading

### ISSUE THREAD

**Issue by fvsch** [kizza/Table-of-comments#39]
Test case:
```css
/* > Test 1 */

/* > Test 2 */

/* > Test 3 */

.test {}

/* Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum. */

.other-test {}
```

When the cursor is placed anywhere after the last heading, the "Move up" command does nothing. In  the test case above, that's when you place the cursor anywhere in lines 6 to 17.

Placing the cursor at the end of the last heading (`/* > Test 3 */|`) works.

**Comment by kizza** [comment]
Cheers @fvsch - a bug, and have fixed in this latest round - will push the new update asap

**Comment by kizza** [comment]
Alright @fvsch the latest release 1.1.5 addresses three of the latest issues you kindly lodged - the two bugs, and the better quick jumping behaviour not going to the top.  

Thanks again for the time suggesting these things for improvement - all great stuff.  That latest version should come down package control soon enough or you can pull the latest version from here.

Cheers (i'll go through and close off these issues now)
