### ISSUE TITLE
Dialog does not focus titles when they're already in current view

### ISSUE THREAD

**Issue by fvsch** [kizza/Table-of-comments#40]
Test case:

```css
/* > 1 Test */
.test_1 {}
/* >> 1.1 Test */
.test_1-1 {}
/* >>> 1.1.1 Test */
.test_1-1-1 {}
/* >>> 1.1.2 Test */
.test_1-1-2 {}
/* >>> 1.1.3 Test */
.test_1-1-3 {}
/* >> 1.2 Test */
.test_1-2 {}
/* >> 1.3 Test */
.test_1-3 {}
```

When a heading is visible in the editor's viewport, focusing its entry in the Toc dialog does not highlight the heading in the code.

Compare with the "Goto Symbol…" dialog, which does highlight symbols that are already visible in the viewport.

I suggest doing things like "Goto Symbol…", if possible.

**Comment by kizza** [comment]
Alright - reckon I've fixed this one too, I had noticed that "sometimes" it didn't always highlight correctly bad hadn't snooped out a testcase - so gracias!  I've now implemented the movement a little differently and seems to be much closer to the gotosymbol approach (also doesn't put the selection at the center of the page etc).  Will push a new release soon.
