### ISSUE TITLE
Headings with comment_chars in main text are discarded

### ISSUE THREAD

**Issue by fvsch** [kizza/Table-of-comments#43]
When using one of the `comment_chars` within a heading, Toc will ignore it.

Test case (with default settings):
```css
/**
 * > Heading goes here
 */

/**
 * > Heading goes *here*. I said HERE. Thanks.
 */

/* >> With a # NUMBER SIGN */
/* >> With a / SOLIDUS */
/* >> With a | VERTICAL LINE */
/* >> With a * ASTERISK */
```

Those characters are likely to appear within the comment's text, for instance when writing:

- `Prev/Next buttons`
- `Redesigned header (issue #57895)`

Users of the plugin might write headings containing one of those characters and wonder why they don't show up in the Table of comments.

The current solution is learning by trial and error that these characters are disallowed. It's not a big deal, but if this friction can be removed, that's even better.

**Comment by kizza** [comment]
Great stuff you're finding @fvsch - and great fixes you're making @ionutvmi!
I've merged that one in
