### ISSUE TITLE
Bikeshedding: use # as level_char

### ISSUE THREAD

**Issue by fvsch** [kizza/Table-of-comments#48]
This is totally one hundred percent bikeshedding, but I thought I'd try. :)

Suggestion: use `#` as the default `level_char` in an upcoming release (1.2?).

Rationale: I think it's a bit more user-friendly to piggy-back on existing conventions. Markdown syntax is well-known among coders, so marking comment headings with `#`, `##`, `###` and so on to signal the heading's level will be familiar.

Other existing conventions: AsciiDoc uses `=`. See [this table on Wikipedia](https://en.wikipedia.org/wiki/Lightweight_markup_language#Prefix) for which plaintext-to-HTML languages uses what.

**Comment by ionutvmi** [comment]
This would cause problems in certain programming languages (python for example) where # is used to start a comment

**Comment by fvsch** [comment]
Good point. (Quick test: with `#` as level char: *all* Python comments are listed as level 1 headings.)
Also I don't find `=` to be a great indicator of level.

So, `>` is intuitive enough and doesn't seem to clash with existing languages or with popular commenting conventions (like `=` or `!` might). I guess it's a keeper. :)
