### ISSUE TITLE
Titles with special characters are ignored

### ISSUE THREAD

**Issue by ewancarr** [kizza/Table-of-comments#5]
Thanks for this package – it's exactly what I was looking for.

One problem: if any of my titles have any special characters (i.e. anything besides A-Z and 0-9) they are ignored. For example:

    * > Heading 1

Works fine, but adding a colon

    * > Heading: 1

means the title will not appear in the TOC.

Is this something I'm doing wrong? Or is this intentional?

**Comment by kizza** [comment]
Howdy @ewancarr - I'm very sorry about my super huge delay, @ionutvmi's update was a perfect solution and is now committed.  I hope it works out for you!

**Comment by ewancarr** [comment]
No problem! Thanks for the update, and thanks @ionutvmi for the fix!

**Comment by ionutvmi** [comment]
No problem,
@kizza if you want you can add me as a contributor on this repo, I'm more then happy to help maintaining it.

**Comment by kizza** [comment]
Cheers dude!  I'm planing to get back into the swing of things so should be fine given the size - but thanks heaps for the support and will certainly keep it in mind!

**Comment by kizza** [comment]
Actually - will do. Appreciate the experience of outside help - and someone else has asked to be involved also. (will just go and find out how to do it now :)

**Comment by MalcolmK** [comment]
Thanks!
You can go to settings, and then on the left there is a sub "collaborators".

**Comment by kizza** [comment]
All done :) Cheers and welcome dude! (hay did you see the new move "up" "down" commands suggested by @cheoAlejo at https://github.com/kizza/Table-of-comments/issues/8).  Is all a bit of fun this github shared plugin stuff.

**Comment by MalcolmK** [comment]
Yeah I did! Awesome man! That was really good feature!

**Comment by MalcolmK** [comment]
Btw, I'm planning to clean up the code a bit, if that's fine with you :)

**Comment by kizza** [comment]
lol - sure! (it's a super small package - what could go wrong!? :)  Two humble requests - firstly can you explain in one to two sentences the nature of the upgrade (purely for me to learn as you seem to be good at this stuff! :) and secondly... what do you do for a crust? (a custom programmer?, web designer? freelancer?).  Just curious is all... i'll be changing from my primary full-time web development employment within a few months so am always interested in what others are doing in this programming language world of ours.

**Comment by ionutvmi** [comment]
> Btw, I'm planning to clean up the code a bit,
I think that would be great 

@kizza I see @MalcolmK already did some branches for the refactoring and develop so I'm sure he will make a pull request before he merges into master and we will have a change to look over it.

**Comment by MalcolmK** [comment]
@ionutvmi yeah ofc! I think it wise to merge everything in the develop branche before merging it with the master branche. That way, all changes can be tested by checking out the develop branche.

@kizza how do you mean "the nature of the upgrade"? You mean what I am planning to refactor?
And I'm a developer. I meanly do PHP, but I am quite interested in most languages. To be honest, I'm not doing very much with Python, but I like the language, so it is more a kind of hobby for me. And I think it is wise to maintain your knowledge of all kinds of languages. You don't have to be good at all languages, but I think it is good to have tasted a lot of them. 
And I am a webdeveloper at werksite.nl. Besides that, I am at school and almost graduating :)

**Comment by kizza** [comment]
(Late reply). Comment wise - no nothing, just wondered if there were some obvious implementation thoughts as am newish to python myself - all super cool. And am a web guy myself (with the same home turf of php - but massively agree that proficiency in other languages opens the mind). Working at full tine at http://www.spectronics.com.au freelancing at http://keiranoleary.com. @ionutvmi you a web guy too?

**Comment by kizza** [comment]
BTW (in case not know) - to push the plugin out to the world via sublime package control a new tag needs to be released with next version number (and allows us to present upgrade notes to the end user https://packagecontrol.io/docs/messaging etc)

**Comment by ionutvmi** [comment]
@kizza yep front end developer for the last year and a half
good catch with the messages on update
I will make a pull request on develop so we have them on the next version
