### ISSUE TITLE
Move by comments

### ISSUE THREAD

**Issue by cheoAlejo** [kizza/Table-of-comments#8]
It could be nice to be able to move by the comments without opening the full table, like the plugin [Move By Symbols](https://packagecontrol.io/packages/Move%20By%20Symbols)

**Comment by kizza** [comment]
Howdy @cheoAlejo - nice idea - having a look at the plugin, do you mean have keyboard shortcuts to move up and down through the comment titles?

**Comment by cheoAlejo** [comment]
Yes, with keybindings. It's a good way to move through the symbos, and it would be great to move up an down through the comment titles. By the way, Table of comments it's a great plugin, made my life easier.

**Comment by kizza** [comment]
Alright - I just coded it all out and pushed a new release which package control should re-pull soon enough (included the "Move By Symbols" keyboard bindings by default - and also via the scrollbar too).  Wow, what a great idea - and it's a perfect addition to the "Table of comments" project! Cheers for getting in touch, I'll find this change very useful myself - and am wonderfully pleased to hear that someone else is getting some value from this plugin :)
